# Generated by Django 3.2 on 2021-05-02 08:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaceni_kategorie', models.CharField(help_text='Zadejte text o maximální délce 50 znaků; text musí být jedinečný', max_length=50, unique=True, verbose_name='Označení kategorie produktů')),
                ('typ', models.CharField(blank=True, choices=[('pušky', 'Pušky'), ('samopaly', 'Samopaly'), ('pistole', 'Pistole'), ('brokovnice', 'Brokovnice'), ('pláty', 'Pláty'), ('helmy', 'Helmy')], default='pušky', help_text='Vyberte označení typu', max_length=20, verbose_name='Typ')),
            ],
            options={
                'verbose_name': 'Typy produktu',
                'verbose_name_plural': 'Typy produktů',
                'ordering': ['oznaceni_kategorie'],
            },
        ),
        migrations.CreateModel(
            name='Prukaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte text o maximální délce 100 znaků', max_length=100, verbose_name='Název zboží')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis produktu')),
                ('cena', models.FloatField(help_text='Zadejte nezáporné desetinné číslo', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cena')),
                ('skupiny', models.IntegerField(blank=True, choices=[(5, 'Skupina A'), (4, 'Skupina B'), (3, 'Skupina C'), (2, 'Skupina D'), (1, 'Skupina E')], default=3, help_text='Vyberte označení průkazu', verbose_name='Skupiny zbrojního průkazu')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Prukaz/%Y/%m/%d/', verbose_name='Fotka produktu')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='munice.kategorie')),
            ],
            options={
                'verbose_name': 'Zbozi',
                'verbose_name_plural': 'Zboží',
                'ordering': ['cena', 'nazev'],
            },
        ),
    ]
