# Generated by Django 3.2 on 2021-05-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prukaz',
            name='skupiny',
            field=models.CharField(blank=True, choices=[('A', 'Skupina A'), ('B', 'Skupina B'), ('C', 'Skupina C'), ('D', 'Skupina D'), ('E', 'Skupina E')], default='A', help_text='Vyberte označení průkazu', max_length=2, verbose_name='Skupiny zbrojního průkazu'),
        ),
    ]
